---
title: "Releasing Our 2026 House Forecast"
description: "How the SnoutCounter House Forecast works"
format: html
draft: true
date: "8/28/2026"
execute: 
  echo: false
categories:
  - 2026 Elections
  - Methodology
  - Forecasts
---

With primary season coming to an end and candidates shifting into gear for the November general, the upcoming midterms and their results are anticipated by everyone from analysts to activists to degenerate gamblers. As we head into general election season, we here at SnoutCounter (and by "we" I mean myself, I'm the only person here) are proud to announce the release of our House forecast, with Senate and gubernatorial forecasts in the works as well. As of the day this is being released, my House forecast gives Democrats a 66% chance of winning the House, with them winning, on average, 229 seats. This is a notably more bearish forecast than most for Democrats, with my projections being comparable to those of [DDHQ](https://votes.decisiondeskhq.com/forecast/2026/house) and [ElectIndex](https://electindex.com/forecasts/) while being significantly more bearish than [The Silver Bulletin/FLIPR](https://www.natesilver.net/p/nate-silver-2026-midterm-election-polls-model), [The Economist](https://www.economist.com/interactive/2026/us-midterms/prediction-model/house), and [FiftyPlusOne](https://fiftyplusone.news/forecast/house). I recommend that you track multiple forecasts and view them holistically rather than relying on any one individual forecast, especially given the large variation in predictions for some seats in particular.

My forecast is a [hierarchical Bayesian linear regression model](https://www.bayesrulesbook.com/chapter-15). The code for this model will be open-sourced from Sept 1 onwards.[^1] Below is the specification for the model that powers the SnoutCounter House forecast.

[^1]: The reason for this is that I've used up my storage limits for GitHub Large File Storage (LFS), so I can't push many of the more recent commits until September 1, when these limits reset.

$$y_{st} = \beta_1b_{st}+\beta_2F_{st}+\beta_3I_{st}+\beta_4\rho_{t-1}F_{st}+\beta_5\rho_{t-1}I_{st}+\beta_6s_{st}+\beta_7n_{st}p_{st}+\beta_8n_{st}b_{st}+\beta_9n_{st}F_{st}+\beta_{10}n_{st}I_{st}+\beta_{11}n_{st}s_{st}+d_t+r_t+\epsilon_t+\alpha_{st}+\gamma_{rt}+\delta_{ct}$$
That's a lot of mathematical notation! So let's break this model down into its constituent parts.

* $y_{st}$ is the response variable, specified as $y_{st}=v_{st}-50$, where $v_{st}$ is the two-party Democratic vote share for congressional district $s$ and election cycle $t$. Setting $y_st$ as the target is equivalent to setting $v_st$ as the target and fixing the intercept term to $\beta_0=50$.
* $\beta_i$ with $i\in[1,11]$ are the regression coefficients.
* $b_{st}$ is the "baseline," an estimate of how the district should vote solely based on PVI and generic ballot. The PVI is calculated as $l_{st}=0.75(v_{s,t-1}-p_{t-1})+0.25(v_{s,t-2}-p_{t-2})$, where $v_{st}$ is the two-party Democratic voteshare for seat $s$ in cycle $t$ and $p_{t}$ is the two-party Democratic share of the popular vote for president in year $t$. The generic ballot term utilized is the margin between Republicans and Democrats in the SnoutCounter generic ballot polling average - you can find how that average is calculated [here](poll-avg-methodology.qmd). We calculate the baseline as $b_{st}=2l_{st}-G_{t}$, where $l_{st}$ is the PVI and $G_{t}$ is the generic ballot margin for year $t$. I multiply the PVI by 2 as the number is a measure of how the district leans in terms of Democratic two-party voteshare - for instance, a district with a PVI of D+1 is estimated to have 51% of its voteshare go to the Democrat in a perfectly even national environment, and all other factors held equal. Thus, a PVI of D+1 implies a margin of D+2. We also swap the sign on $G_{t}$ as it is calculated as the Republican polling average minus the Democratic polling average, i.e. $G_{t}$ is negative when Democrats have the advantage, whereas $l_{st}$ is positive when Democrats have the advantage in seat $s$.
* $F_{st}$ represents fundraising for a seat-level race. It is calculated as the difference between percentages of individual contributions donated of the Democrat and the Republican. $F_{st}$ is positive if the Democrat has received a greater share of individual contributions than the Republican, and is set to zero if neither the Democrat or Republican have filed finance reports with the FEC, or if neither candidate has been determined (i.e. pending a primary election result).
* $I_{st}$ represents incumbency. It is set to 1 if the Democrat is the incumbent, -1 if the Republican is the incumbent, and 0 if neither or both candidates are incumbents.
* $\rho_{t}$ represents polarization. It is calculated as the correlation between two-party Democratic voteshare for the most recent presidential election and the two-party Democratic voteshare in House elections in cycle $t$. Incumbency and fundraising generally tend to have lesser influence in more polarized cycles, so I utilize this term to adjust their influence in accordance with polarization.
* $s_{st}$ is the "net scandal score" for a certain race. Each politician in a race is assigned a "scandal score", which counts up the number of scandals that the aforementioned politician has faced over the course of their political career, weighted by an exponential decay function to place less weight on older scandals that a politician has weathered. The net scandal score is the scandal score of the Democrat minus the scandal score of the Republican.
* $n_{st}$ and $p_{st}$ relate to the race-level polling for seat $s$. $n_{st}$ is calculated as $n_{st}=\sqrt{N_{st}}$, where $N_{st}$ is a measure of the effective number of polls (ENOP) - essentially, the number of polls weighted by pollster quality and recency. A race with more polls, higher quality polls, and that have been polled more recently will have a higher ENOP. $p_{st}$ is simply the margin between the Republican and the Democrat. The higher the ENOP of a race, the more weight is placed on race-level polling, and the less weight is placed on fundamentals.
* $d_t$ and $r_t$ are random effects that correspond with the Democratic and Republican candidate, respectively. These account for routine electoral over- and under-performers.
* $\epsilon_t$ is a random effect that accounts for cycle-level error, e.g. industry-wide systemic polling error, like that which occurred in 2020.
* $\alpha_{st}$ is a random effect that accounts for state-level error, e.g. idiosyncratic trends at the state level, such as the localized red waves in New York and Florida in 2022.
* $\gamma_{rt}$ is a random effect that accounts for region-level error. I utilize [census regions](https://en.wikipedia.org/wiki/List_of_regions_of_the_United_States) for this term. For instance, if the Democrat generally overperforms in the Midwest, this random intercept will capture that.
* $\delta_{ct}$ is a random effect that accounts for error at the level of a "demographic cluster." I constructed a [k-means clustering](https://en.wikipedia.org/wiki/K-means_clustering) algorithm to categorize all districts in the training data into seven clusters based on racial composition, educational attainment, and urbanization. This accounts for idiosyncratic trends among certain demographics, for instance the right-ward swing of Hispanic voters in 2024, or the left-ward swing of college-educated voters in 2018.

The non-candidate random effects $\epsilon_t$, $\alpha_{st}$, $\gamma_{rt}$, $\delta_{ct}$ ensure that errors are correlated, which is especially helpful for posterior simulation. I train this model on all House elections from 2014-2024 (excluding seats that were not contested by one party for whatever reason). Certain independents (for example, [Cara Mund](https://en.wikipedia.org/wiki/2022_United_States_House_of_Representatives_election_in_North_Dakota) in 2022 and Bill Hill in 2026) are considered to be part of one party or the other for training and prediction reasons. I set the priors for the coefficients to autoscaled student's t distributions, which accounts for outliers and heteroskedasticity, and utilize the [Markov chain Monte Carlo](https://en.wikipedia.org/wiki/Markov_chain_Monte_Carlo) method to generate 20,000 simulations of how the upcoming House elections could go.